### ISSUE TITLE
Country of Origin Added to Fertilizer for GHG calculations

### ISSUE THREAD

**Issue by RonColes** [holos-aafc/Holos#146]
### Feature request.

When comparing local organic nutrient sources to synthetic fertilizers it would be ideal to include production emissions.

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by RKroebel** [comment]
Hi Ron, 
the upstream emissions for the production of synthetic fertilizers are already in the model (as far as we could find them). For organic nutrient source,  we dont have info on where they are coming from, and from the carbon footprint accounting methodology, most of those emissions would be associated with who produced it. Currently, this allocation would have to be done outside Holos, if you have data that could be included, please let us know.

**Comment by RonColes** [comment]
Thank You. Is there a link to the values used for upstream emission values?

**Comment by holos-aafc** [comment]
The values that Holos uses can be found here:

https://github.com/holos-aafc/Holos/blob/main/H.Content/Resources/Table_48_Carbon_Footprint_At_Plant_Gate_For_Direct_Fertilizer_Blends.csv

**Comment by RonColes** [comment]
Is this for production source? N2O-N_____	N2O emission source/summary (kg N2O-N ha-1)

And Holos uses the assumption all fertilizers are produced in North America?

**Comment by RKroebel** [comment]
Hi Ron,
this table represents the carbon footprint of produced fertilizers as the factory gate (transport to the farm is not currently considered), and we utilize North American/US numbers, as we assumed that production practices in Canada vs US do not differ much. The emissions are output as CO2 eq, and Holos outputs them as upstream emissions. The N content of those fertilizers is then added to the N2O emissions calculations and reported as direct and indirect N2O emissions (on-farm emissions) and reported as either kg N2O or alternatively in CO2eq.

**Comment by holos-aafc** [comment]
Hi Ron, has your questions been answer with regard to country of origin emissions? I'll close this item if so.
