### ISSUE TITLE
ICBM - Deviation from Holos V4.0 technical report, section 2.1.2.6.2

### ISSUE THREAD

**Issue by L-HEREDIA-LOGIAG** [holos-aafc/Holos#150]
### Your suggestion.

Good morning
Technical documentation proposes the following condition: Cr(t) < Cr(t-1) to activate both equations 2.1.2-32 and 33.
By looking at the current code [ICBMSoilCarbonCalculator](https://github.com/holos-aafc/Holos/blob/d1e66da2931326c57e3eede012b7f4994c06b356/H.Core/Calculators/Carbon/ICBMSoilCarbonCalculator.cs), it looks like condition is replaced by Ce(t)<Ce(t-1) and equation eq. 2.1.2-32 is removed.

Do you confirm the new behaviour in this subsection of ICBM module?
Have a great day, Ludovic

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by holos-aafc** [comment]
Hi @L-HEREDIA-LOGIAG,

I can confirm that 2.1.2-32 is no longer used in the code. The equation remains in the algorithm document as a placeholder and might be removed from the document in the future.

Thanks,
Aaron

**Comment by L-HEREDIA-LOGIAG** [comment]
Great. Thank you Aaron for the validation
