### ISSUE TITLE
ICBM - Missing information from table 07-Relative_Biomass_Information

### ISSUE THREAD

**Issue by L-HEREDIA-LOGIAG** [holos-aafc/Holos#151]
### Contact Details

ludovic.heredia@logiag.com

### Your suggestion.

Section 2.1.2 of technical Holos documentation v4 extract crop parameter values from [table 7](https://github.com/holos-aafc/Holos/blob/main/H.Content/Resources/Table_7_Relative_Biomass_Information.csv) to calculate carbon inputs.

For some crops, parameters are empty (example: Vegetables or Phacelia) so we wonder how calculations deal with missing data. Is there any hypotheses we can access?

Thank and have a good day, Ludovic

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by RKroebel** [comment]
hi Ludovic, 
crops that have missing parameters are not read into the model and are currently there as placeholder (aka, we have some numbers to get this crop added, but not all, so maybe a 'low-hanging fruit' for folks that want to help expand the table.

PS: Hassan Afzaal is no longer with us, unfortunately.

**Comment by L-HEREDIA-LOGIAG** [comment]
Thank you for you answer. For now, it is not a big concern as there is low chance for us to use those crops for which data are missing. In our model, we fill the gaps with averaging or similar crops.

I'll let you know if we find reliable sources to improve this table.
L.
