### ISSUE TITLE
ICBM: Need some understanding of equation 2.1.1-11 of the technical documentation V4.0

### ISSUE THREAD

**Issue by L-HEREDIA-LOGIAG** [holos-aafc/Holos#152]
### Contact Details

ludovic.heredia@logiag.com

### Your suggestion.

Good morning.

In our process to understand the ICBM algorithm, we are facing with issues for the equation 2.1.1-11: SoilMeanDepth = SoilTopThickness/20.
We are not sure if we are talking about the whole soil top thickness which is indeed about 25 cm by comparing with other studies, or a very thin layer of it. We are more inclined to go with the first scenario, however in that case we would divide the soil top thickness by only 2.

By any chance, do you have a reference/source which explain this equation?

Thank you very much. Ludovic

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by RKroebel** [comment]
Hi Ludovic,
The ICBM inclusion was accomplished on the basis of a contract issued to Martin Bolinder (who works(ed) closely with T. Kaetterer and authored a number of papers detailing how ICBM can be used in Canada. His report is attached, but there is no further info in there about the soil depth question you're having. You'd have to dig deeper into Bolinder's ICBM publications, or possibly going back all the way to Andren & Kaetterer.
[ICBM equations 15June2018.docx](https://github.com/user-attachments/files/16144922/ICBM.equations.15June2018.docx)

**Comment by L-HEREDIA-LOGIAG** [comment]
That is fine, I'll ask someone in my team to take some time to investigate this problem. 
I'll share with you interesting findings about this equation, if any.

Thank you Roland
