### ISSUE TITLE
Effect of evolution of soil organic matter content in Re calculation

### ISSUE THREAD

**Issue by L-HEREDIA-LOGIAG** [holos-aafc/Holos#153]
### Contact Details

ludovic.heredia@logiag.com

### Your suggestion.

Hello again, i have one last question on my list.

Since the soil organic matter is evaluated each year in section 2.1.3 of holos documentation v4.0, I wonder if the SoilOrganicC_Percent input in equation 2.1.1-4 is adjusted with some kind of ratio or it is left constant over the years? To be clear, I'm talking of a ratio because i think there is a linear relation between the SoilOrganiC_percent and SOCt, heavily impacted by the soil 'apparent density'.

Have a good day, Ludovic

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by holos-aafc** [comment]
Hi Ludovic,

The value being used is constant over the years. It is a value taken from SLC database:

https://sis.agr.gc.ca/cansis/nsdb/soil/v2/slt/orgcarb.html

I don't believe we have a method to adjust this value over the years. We are open to suggestions though.

Thanks,
Aaron

**Comment by L-HEREDIA-LOGIAG** [comment]
Thank you very much, that's clear for me.

For now we are opting for the same approach. We may evaluate in the future the influence of organic matter dynamic in Re calculation, but I don't think/hope it has a strong impact on calculations.

Ludovic
