### ISSUE TITLE
Type of Ash Content Required in the Beef Diet Management Section

### ISSUE THREAD

**Issue by sgorain** [holos-aafc/Holos#163]
### Your suggestion.

Under section 3 Beef Production, sub section Diet Management, the Ash content of manure is listed as a parameter, Should this be ash content of the feed?

Here is the page I am referring to: https://github.com/holos-aafc/Holos/blob/main/H.Content/Documentation/Input%20Requirements/Input_Requirements_v4.md

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by holos-aafc** [comment]
Thanks for reporting this
