### ISSUE TITLE
(ICBM) 'Growing season precipitation/evapotranspiration' output in Multiyear_Results.csv output file

### ISSUE THREAD

**Issue by L-HEREDIA-LOGIAG** [holos-aafc/Holos#178]
### Contact Details

ludovic.heredia@logiag.com

### Expected Behaviour

Hello Holos Teams.

We have a question regarding simulation results from the ICBM module. In the multiyear_result_test.cvs, there are two outputs: 'Growing season precipitation (mm year^-1)' and 'Growing season evapotranspiration (mm year^-1)' which gives same results for different years in our tests. For example 632.902 mm for 1985 to 1987, then 422.26 mm, then it cycles back to 632.902 mm.

However, from our understanding, Holos 4.0 extracts daily climatic data from NASA database so we are expecting different values for these outputs, for every year. Do you mind to give us some explanations why those output do not give what we are expecting?

I have attached a .csv file with this report, hope it's available for you.
Thank you a lot again, Ludovic

[Multiyear_Results_test.csv](https://github.com/user-attachments/files/16998344/Multiyear_Results_test.csv)

### Actual Behaviour

These variables can give the same values for severral years

### Describe the Issue & Steps to Reproduce

1. Simulate corn grain on one field since 1985
2. Create a multiyear_results.csv file when analysing ICBM related results

### Error Message

No error message, unexpected behaviour

### Holos Version Number

4.0 (last version is automatically downloaded when launched)

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Could you export the farm file and send to the Holos email account or attach here if possible.

Thanks

**Comment by L-HEREDIA-LOGIAG** [comment]
[LOGICBM REV04-ANNUAL_CROP_NO_20232024-SOIL_ADJUSTED.json](https://github.com/user-attachments/files/16998777/LOGICBM.REV04-ANNUAL_CROP_NO_20232024-SOIL_ADJUSTED.json)

**Comment by holos-aafc** [comment]
Hi @L-HEREDIA-LOGIAG . Holos will download daily climate data from NASA for the farm's location. We have found that sometimes NASA does not return a full set of daily climate data - sometimes there are days missing from the year in question. When NASA returns a set of values representing any particular year, and there is data missing from that set, Holos will revert/fall back to using annual climate normals instead. This is what is happening on this farm and why you see repeating values for some years.

I am open to suggestions on how to improve the default response to these scenarios if you have any feedback. 

Thanks

**Comment by holos-aafc** [comment]
There is another issue with the climate data that has just been fixed. Sometimes NASA is returning data for 366 days in some years and this was not being accounted for in Holos. An update will be made available to fix these issues later this week. I will include more information on the fix when the update is ready

**Comment by holos-aafc** [comment]
Hi @L-HEREDIA-LOGIAG . This issue has been fixed with [#d43e527](https://github.com/holos-aafc/Holos/commit/d43e5273514f39b9a7a35277a6731e30dcbb5c2d) . The GUI will download this update when you restart Holos.

https://github.com/holos-aafc/Holos/blob/main/Changelog.md

Thank you for reporting this issue.
