### ISSUE TITLE
Hog default enteric CH4 rates and start/end weights in Farrow-to-Finish production system

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#198]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

The default enteric CH4 emission rates for Hogs (i.e., Grower/Finisher) animals in the Farrow-to-Finish component should be the same as those for the Hogs in the Grower-to-Finisher component, i.e., different based on their weight category. These lookup values can be found in Table 27 in the alg doc/GitHub. All default values for Hogs (grower/finisher) animals should be the same, regardless of which component they are in (i.e., Grower-to-Finish or Farrow-to-Finish); his also goes for the start and end weights for the different Hog management periods in the Farrow-to-Finish component - these are currently incorrect and should be the same as in the Grower-to-Finish component.

### Actual Behaviour

The default enteric CH4 emission rate for Hogs in the Farrow-to-Finish component is 2.64 for all management periods/weight categories, which is incorrect. The start and end weights for each of the Hog management periods in the Farrow-to-Finish component are also a little off - these should be the same as the weights in the Grower-to-Finish component for each management period.

### Describe the Issue & Steps to Reproduce

Add a Farrow-to-Finish component and go to the 'Hog' animal group and the incorrect default values are displayed.

### Holos Version Number

4.0.1.1

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
New components will have the updated start/end weights for hogs and the resultant CH4 rates depending on weight of the hogs
