### ISSUE TITLE
Eq. 4.3.1-8: indoor barn temperature for ATAfeedlot calculation

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#203]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expect Eq. 4.3.1-8 to use the indoor dairy barn temp data when calculating ATAfeedlot, but it appears to be using the outdoor ambient temperature from NASA instead. 
Can you please confirm that Holos is using the indoor barn temperature data in Table 63 when calculating ATAfeedlot (for housing NH3-N emissions) for all indoor dairy cattle housing systems (i.e., tie-stall, free-stall, milking parlour). For the same equation, Holos should use the outdoor NASA temp data for all outdoor housing, i.e., drylot or exercise yard for dairy cattle and confined no barn (feedlot) for beef cattle. 

Please find attached the test Holos farm file and the corresponding Excel version of the calculations for the same farm setup - see rows 61-79 in the "Summary_Solid_LiquidIndirectN2O" worksheet in the "HolosV4ModelTesting_DairyCattle AllEstimates_CURRENT.xlsx" file attached, and column O in the "SolidIndirN2O_LactatingDryCows" worksheet (which uses the Table 63 temp data).

[HolosV4ModelTesting_DairyCattle_ AllEstimates_CURRENT.xlsx](https://github.com/user-attachments/files/17757669/HolosV4ModelTesting_DairyCattle_.AllEstimates_CURRENT.xlsx)

[HolosV4ModelTesting_Dairy_SolidManure.json](https://github.com/user-attachments/files/17757681/HolosV4ModelTesting_Dairy_SolidManure.json)

### Describe the Issue & Steps to Reproduce

1. Open attached farm file and click through to the Results > Manure Management Report > Housing NH3-N emissions
2. Compare the Housing NH3-N emissions estimates from Holos with the corresponding estimate in the Excel file (rows 61-79 in the "Summary_Solid_LiquidIndirectN2O" worksheet and column O in the "SolidIndirN2O_LactatingDryCows" worksheet (which uses the Table 63 temp data).

### Holos Version Number

4.0.1.1

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Will be fixed in version 4.0.1.5. Indoor dairy housing no longer gets an additional +2 degrees added to indoor temperatures
