### ISSUE TITLE
Eq. 4.3.2-4 and Eq. 4.3.2-5 - temperature adjustment for NH3-Nstorage emissions from stored dairy manure

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#204]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expect Eq. 4.3.2-4 and 4.3.2-5 to use the ambient daily outdoor temperature (from NASA) when calculating the temperature-based adjustment for NH3-Nstorage emissions. 

### Actual Behaviour

It appears that Eq. 4.3.2-4 and 4.3.2-5 are using the indoor barn temperature (from Table 63) to calculate the temperature-based adjustment for NH3-Nstorage emissions. **Aaron:** can you please verify this? If this is the case, the code should be changed so that these two equations use the outdoor temperature data from NASA instead for dairy cattle storage NH3-N emissions. 
The indoor barn temperature data from Table 63 should only be used in relation to housing NH3-N emissions for dairy cattle in tie-stall barns, free-stall barns or milking parlours. 

### Describe the Issue & Steps to Reproduce

See attached dairy farm file and corresponding Excel file; see rows 102-119 in the "Summary_Solid_LiquidIndirectN2O" worksheet and column X in the "SolidIndirN2O_LactatingDryCows" worksheet - note that in column X I am using the outdoor NASA temperature which leads to a mismatch between the Holos and Excel estimates in rows 102-119 in the "Summary_Solid_LiquidIndirectN2O" worksheet.

[HolosV4ModelTesting_DairyCattle_ AllEstimates_CURRENT_1.xlsx](https://github.com/user-attachments/files/17803899/HolosV4ModelTesting_DairyCattle_.AllEstimates_CURRENT_1.xlsx)

[HolosV4ModelTesting_Dairy_SolidManure.zip](https://github.com/user-attachments/files/17803913/HolosV4ModelTesting_Dairy_SolidManure.zip)

### Holos Version Number

4.0.1.1

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Fixed in v 4.0.1.6

4186ac7f3e851db8f7ff73ebdd6e244d5a714d74
