### ISSUE TITLE
GUI Export for CLI

### ISSUE THREAD

**Issue by ramsaym** [holos-aafc/Holos#27]
### Feature request.

In order to use the open source CLI as an exposed service, it is requested that files exported by the GUI can be directly importable to the CLI, allowing modelers to configure farming systems in the gui, but modify and process them using the CLI in an automated environment (windows cmd, linux, etc). The request is for the purposes of running sensitivity analysis on parameters such as decomp rates, volatilization co-efficients, and being able to programmatically configure and run multiple reports or merge reports into single datasets using other command line tools. 

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by aaron-mcpherson** [comment]
@ramsaym in the GUI, you can export farm files as .json. When running the CLI, it will ask if there are farms from the GUI that you want to import/use in the CLI. Is this the functionality you are looking for here?

**Comment by UrsakiUleth** [comment]
Hello @ramsaym.

You can refer to these two sections of the user guide to help with your issue:
1. Exporting farm(s) from the Holos GUI: https://github.com/holos-aafc/Holos/blob/main/H.Content/Documentation/User%20Guide/User%20Guide.md#exporting-farms
2. Importing farm(s) to the Holos CLI:  https://github.com/holos-aafc/Holos/blob/main/H.Content/Documentation/User%20Guide/User%20Guide.md#using-the-command-line-interface

Step 3 under Using the Command Line Interface (second link provided) contains some extra guidance on importing the .json version of your farm you have exported from the GUI, ie: where to save your exported .json farm.

Let me know if you have any more questions.

**Comment by ramsaym** [comment]
Apologies on the delay I hadn't seen this. That is the functionality, but when I last used it it wouldn't work. Had a lot of incorrect values in fields. So if that's been resolved I should be good to go. -MattOn Sep 5, 2023, at 11:35 AM, UrsakiUleth ***@***.***> wrote:Closed #27 as completed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
