### ISSUE TITLE
CLI Crashes When Importing from JSON

### ISSUE THREAD

**Issue by Miumimu** [holos-aafc/Holos#36]
### Contact Details

miumahjabin@gmail.com

### Expected Behaviour

Importing from the exported JSON file(from GUI) proceeds without any error.

### Actual Behaviour

1. When importing the generated JSON file in the CLI project, it seems like the values in the CSV files do not match the corresponding column. For example, in one case, the Cover Crop Type column values are all FALSE. Whereas the permitted values are OptionA, OptionB, and OptionC, I guess(as far as I understood from the code). In another case, the values in the column Cover Crop Termination Type seemed like GUID, which I think is more suitable for the column Field System Component Guid.
2. A minor issue I found, when I tried to name something which contained a slash(/). It might be due to the ambiguity when creating folders, as Windows separates folders in the file path using a slash.
3. The Animal Types in HOLOS 4 GUI does not match with Animal Types in the CLI project.

### Describe the Issue & Steps to Reproduce

[My Exported Farms.zip](https://github.com/holos-aafc/Holos/files/12173930/My.Exported.Farms.zip)

1. Unzip the attached file.
2. Run the HOLOS CLI project in debugging mode.
3. Import the unzipped JSON file from the CLI project.

### Error Message

![Row 42 column Error](https://github.com/holos-aafc/Holos/assets/57233032/89d660f8-d63f-4a4f-a545-d20f44b091d1)
![Back slash Error](https://github.com/holos-aafc/Holos/assets/57233032/ef381604-c982-4199-b5fa-cc4eb600c9f2)

### Holos Version Number

4.0.0.467

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
For #2, can you remove the forward slash in the .csv filename to see if that is the issue. Try "Tame mixed (grass-legume)" instead of "Tame mixed (grass\legume)"

**Comment by Miumimu** [comment]
Hi,
For #2, the program crashes when generating the CSV files. So in this case, CSV files are not available yet. I guess one workaround can be editing the JSON file directly. But I am not sure which field is being used to name the CSV Files.

**Comment by Miumimu** [comment]
> For #2, can you remove the forward slash in the .csv filename to see if that is the issue. Try "Tame mixed (grass-legume)" instead of "Tame mixed (grass\legume)"

Hi,
For https://github.com/holos-aafc/Holos/discussions/2, the program crashes when generating the CSV files. So in this case, CSV files are not available yet. I guess one workaround can be editing the JSON file directly. But I am not sure which field is being used to name the CSV Files.

**Comment by Miumimu** [comment]
Thank you very much. I have created a Pull Request(https://github.com/holos-aafc/Holos/pull/37) with the change you suggested. I am not sure if my change adheres to your conventions. Please let me if you think I need to change anything.

**Comment by holos-aafc** [comment]
Can you also create an associated unit test in the H.CLI.Test.Processors.FieldProcessorTest class that tests some default scenarios for correctness? Thank you

**Comment by Miumimu** [comment]
Thank you very much for your suggestion. I have relocated the method to H.Infrastructure.FileSystemHelper.cs and have written test cases as well.

**Comment by holos-aafc** [comment]
Thank you. I'm looking into the the remaining items for this issue

**Comment by holos-aafc** [comment]
Runs to completion without crashing now

**Comment by Miumimu** [comment]
It seems to be the same problem for Poultryt as #1.
The GUI Poultry options don't match the code. 

![ChickenPullets not an animal type](https://github.com/holos-aafc/Holos/assets/57233032/8cc3b3d4-cc64-4531-adaf-45d765a12eff)
![HOLOS GUI Poultry](https://github.com/holos-aafc/Holos/assets/57233032/3ca44e68-a613-4fb1-be04-daf43b148b7d)
![Poultry in code](https://github.com/holos-aafc/Holos/assets/57233032/552dc792-9182-4aff-9195-e90d52b99719)

**Comment by holos-aafc** [comment]
Can you include the farm file for this scenario

**Comment by Miumimu** [comment]
No, I tried a different farm and found this issue. Here is it- 

[My Exported Farms.zip](https://github.com/holos-aafc/Holos/files/12185384/My.Exported.Farms.zip)
