### ISSUE TITLE
Data displayed in Results > Manure Management

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#38]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

On the "Manure Management" window on the Results screen, I have note the following potential issues:
•	The “Amount of TAN entering storage (kg TAN)” and the “Adjusted amount of TAN entering storage (kg TAN)” are the same value, but I think they should be different as they are estimated using Eq. 4.3.2-1 and Eq. 4.3.2-2, respectively (for beef cattle, as an example) – please see the Manure Management window in the attached farm file – for Beef Cow-Calf > Bulls > Winter feeding > January: the TAN entering storage and the Adjusted TAN entering storage are the same value. If this is due to the previously incorrect equations to estimate FaecalN, then hopefully this will be corrected once those changes have been made in the code;
•	The “TAN available for land application (kg TAN)” decreases from month to month when I think it should increase, as the “Adjusted amount of TAN entering storage (kg TAN)” on day d is added to the amount of TAN in storage on day d-1 (Eq. 4.3.2-2 and 4.3.2-3). I do need to make an edit to section 4.3.2.1 to incorporate the equation to estimate the amount of NH3-N lost during the storage stage (e.g., this is currently located in section 4.5.2.1 (Eq. 4.5.2-1) for beef cattle), but we should still have a net increase in the amount of TAN (and faecal N and total N) in stored manure over time, assuming no manure is removed from the storage system).

### Describe the Issue & Steps to Reproduce

These issues occurred during the normal running of a farm file in Holos - file sent to Aaron via email.

### Holos Version Number

4.0.0.468

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
For the first issue:

In the farm file attached, I had a look at the results for the heifers group in the Dairy component. The manure management option for that group was set to "pasture/range/paddock" on the manure tab. In this case, we don't currently have values for fraction immobilized, fraction mineralized, fraction nitrified, or fraction denitrified in table 44 (code). 

https://github.com/holos-aafc/Holos/blob/main/H.Core/Providers/Animals/Table_44_Fraction_OrganicN_Mineralized_As_Tan_Provider.cs

Is there associated values for pasture/range/paddock that I missed? 

I verified that this was the issue by changing the manure handling system for the group to 'deep bedding'.

**Comment by sarahp1980** [comment]
Thanks Aaron for clearing things up on the first issue. For pasture/range/paddock systems, there isn't really any "storage" of manure, as it is deposited directly in the field. For this housing/manure management system, we can discuss with Roland if we want to report "storage" values.

**Comment by holos-aafc** [comment]
The TAN, ON, and manure N columns (under the land application section of the report0 now show the accumulated totals spanning the entire management period (instead of the amounts created in the specific months as displayed before).

The negative values being shown for the mid lactation period are caused by the pasture/range/paddock setting being used for the housing.

This is reflected in latest update ready for download now.

![sshot-116](https://github.com/holos-aafc/Holos/assets/95769272/59761286-9b11-47cd-b306-98869af2baaa)

**Comment by sarahp1980** [comment]
Thanks for the update.
