### ISSUE TITLE
Horizontal scrolling in Results > Manure Management

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#39]
### Feature request.

- The ability to scroll horizontally on the Results > Manure Management screen;
- Fixed headings when scrolling down on the Results > Manure Management screen;
The above points can also apply to any other screens where these functions are not currently available.

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by sarahp1980** [comment]
Thanks Matthew!

**Comment by holos-aafc** [comment]
This is reflected in latest update ready for download now.
