### ISSUE TITLE
Incorrect no. of days after setting start and end dates

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#44]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expect the "Number of days" under Step 2 on the Component Selection screen to be correct after setting a specified start and end date.

### Actual Behaviour

After setting the start and end date, the Number of days is sometimes not correct, e.g., after setting the start and end dates as 01-01-2022 and 31-12-2022, respectively, the Number of days is not 365 days.
![HolosStartEndDateIssue_14Aug2023](https://github.com/holos-aafc/Holos/assets/112989918/cf677196-e2c4-428a-a411-a4bce1981629)

### Describe the Issue & Steps to Reproduce

1. Start and end dates set to 01-01-2022 and 31-12-2022, respectively, and incorrect Number of days displayed;
2. Typically, if I change the end date to 30-12-2022 (it sometimes then estimates the no. of days as 1) and then change back to the correct end date (31-12-2022), then I get the correct 365 days. This is what usually happens, but sometimes it gives me the correct no. of days on the first try.
It does seem a little random. Sometimes playing with the start date solves the issue, other times changing the end date fixes it. 

### Error Message

No error message

### Holos Version Number

4.0.0.468

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
This is fixed in the latest version. Could you verify the fix before I close this ticket?
