### ISSUE TITLE
Screen freezing when trying to set simulation period to 1995

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#45]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expect Holos to set the simulation period to 1995 when the start and end dates are set as 01-01-1995 and 31-12-1995, respectively.

### Actual Behaviour

The program freezes and I need to shut down and restart Holos.

### Describe the Issue & Steps to Reproduce

1. Start and end dates set to 01-01-1995 and 31-12-1995

### Error Message

No error message - Holos just freezes

### Holos Version Number

4.0.0.468

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by aaron-mcpherson** [comment]
I tested this version 4.0.0.475 (latest GUI release) with a management period starting in 1995 and ending in 2023. It takes a few seconds to calculate 10K+ days of emissions but it should be faster than before now. Can you verify? Thanks
