### ISSUE TITLE
Incorrect manure N estimate on 'manure N dial' in land management components

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#47]
### Contact Details

sarahpogue@gmail.com

### Your suggestion.

The amount of total N in stored manure available for land application on the manure dial on the 'Manure' tab for field/crop rotation components in the Component Selection screen should match the sum of the estimates for the relevant manure types in the "Total manure N available for land application (kg N)" column in Results > Manure Management. Instead, the estimates for total N in stored manure are different on the two screens indicated.
The incorrect manure N values are also leading to incorrect estimates for "Total volume of manure (Wet weight)" on both screens.
I suggest that the code be changed so that the total manure N and volume manure N estimates on the manure dial in the field component are estimated using the same approach as the values reported in the Results > Manure Management screen (assuming these are correct values).

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by aaron-mcpherson** [comment]
Fixed in version 4.0.0.475
