### ISSUE TITLE
C and N in bedding not calculated

### ISSUE THREAD

**Issue by sarahp1980** [holos-aafc/Holos#49]
### Contact Details

sarahpogue@gmail.com

### Expected Behaviour

I expect the amount of Bedding C and Bedding N reported on the Results > Manure Management screen to be non-zero if I specify a bedding type and non-zero application rate on the Housing tab on the Component Selection screen.

### Actual Behaviour

The Bedding C (kg) and Bedding N (kg) are zero on the Manure Management screen for the 'Maintenance boars' and 'AI boars' animal groups in the attached Holos V4 farm file, even though I have specified 'Straw (chopped)' bedding at the the default application rate of 0.79 kg per head per day. 
[Manitoba 1995 farrow to wean_SJP.txt](https://github.com/holos-aafc/Holos/files/12412835/Manitoba.1995.farrow.to.wean_SJP.txt)

### Describe the Issue & Steps to Reproduce

No specific steps - just normal farm setup

### Holos Version Number

4.0.0.478

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by aaron-mcpherson** [comment]
In the latest version, changing the bedding type from 'None' to another type of bedding will update the C/N outputs on the manure management screen
