### ISSUE TITLE
A minor typo in Crop Rotation form

### ISSUE THREAD

**Issue by AnhaytAnanun** [holos-aafc/Holos#5]
### Contact Details

nikolay.sargsyan@carbonassetsolutions.com

### Expected Behaviour

"Click the 'Add Crop' button to adds crops to this rotation" should be "Click the 'Add Crop' button to add crops to this rotation".

### Actual Behaviour

There is a typo in the "Click the 'Add Crop' button to adds crops to this rotation" text, should be "add" instead of "adds".

### Describe the Issue & Steps to Reproduce

1. Start a Holos project as usual.
2. Add a "Crop Rotation" item to your farm.
3. The typo can be observed.

### Holos Version Number

4.0.0.348

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Thanks for reporting this Nikolay. This has been corrected.
