### ISSUE TITLE
Installation package for Holos CLI

### ISSUE THREAD

**Issue by gfortinLogiag** [holos-aafc/Holos#50]
### Feature request.

Is there an installation package for the CLI version of Holos? 

From the documentation, it looks like a very powerful feature to model multiple farms, but it is unclear how to launch it.

Thanks!

Guillaume

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by aaron-mcpherson** [comment]
Hi Guillaume,

At the moment, the CLI can only be launched by using Visual Studio and compiling the CLI source code. I will make an installer package soon (similar to the installer for the GUI)

**Comment by aaron-mcpherson** [comment]
The installer for the CLI can be found at this link: 

[](https://agriculture.canada.ca/holos/cli/setup.exe)

**Comment by gfortinLogiag** [comment]
Thanks a lot for the very quick response!
