### ISSUE TITLE
Configuration file to select ICBM model and associated options in Holos CLI

### ISSUE THREAD

**Issue by gfortinLogiag** [holos-aafc/Holos#51]
### Feature request.

I have run a test farm through the Holos CLI for an cases where I am mainly interested in looking at the Soil Organic Carbon. It appears that Holos CLI defaults to IPCC Tier 2 for SOC modeling and I cannot find an option to select ICBM. Can this be enabled, with all the same options present in the GUI?

I also see small differences in initial SOC and large differences in trends between the Holos GUI and Holos CLI results for IPCC Tier 2, whcih may be  caused by significant differences in carbon inputs. For a specific historical year (2017), I see: 
* Above Ground Carbon Input (i_ag) (kg C ha^-1): 3675.7 in GUI results vs. 4117.31 in CLI results
* Below Ground Carbon Input (i_bg) (kg C ha^-1): 918.93 in GUI results vs. 2367.83 in CLI results
* Manure Carbon Input (i_m) (kg year^-1): 943.88 in GUI results vs. 0 in CLI results
* Digestate carbon input (kg year^-1): 0 in both GUI and CLI

The source of these differences is unclear as the reported carbon inputs from product, straw, roots and extra-roots are identical in both GUI and CLI result files. The files are attached in case it may be useful.

I am filing this as a feature request rather than a bug report as the difference in results is very likely due to different settings and it highlight the need for enhanced control over Holos CLI execution.

Thanks!

[Multiyear_carbon_modelling_CLI.csv](https://github.com/holos-aafc/Holos/files/12580985/Multiyear_carbon_modelling_CLI.csv)
[Multiyear_carbon_modelling_GUI.csv](https://github.com/holos-aafc/Holos/files/12580986/Multiyear_carbon_modelling_GUI.csv)

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by gfortinLogiag** [comment]
Thanks for the quick response!

I have tried adding the new argument but I am not seeing any difference whether I specify "Carbon modelling strategy = ICBM" or  "Carbon modelling strategy = IPCCTier2". In both cases, the SOC results are identical. They are similar to the results I was getting yesterday but still significantly different between the new (49000 kg C ha^-1) and the old version (52000 kg C ha^-1).

I am attaching the json file for the test farm exported from the GUI.
[Logiag_test_farm.zip](https://github.com/holos-aafc/Holos/files/12591105/Logiag_test_farm.zip)

Thanks again for your assistance!

**Comment by aaron-mcpherson** [comment]
@gfortinLogiag the previous updates related to the addition to the settings file were in the code only - not the CLI installation package.

A new installation package for the CLI is now ready.

Once you set the "Carbon modelling strategy = ICBM" key, Holos should output identical results that were noted in the GUI.

One thing to note is that the two different C models (ICBM and IPCC Tier 2) will calculate C inputs using different methods. 

> They are similar to the results I was getting yesterday but still significantly different between the new (49000 kg C ha^-1) and the old version (52000 kg C ha^-1).

This will result in differences being seen in the total C estimated in the outputs (i.e. 49000 and 52000 kg ha^-1 as you noted above).


>    Above Ground Carbon Input (i_ag) (kg C ha^-1): 3675.7 in GUI results vs. 4117.31 in CLI results
>    Below Ground Carbon Input (i_bg) (kg C ha^-1): 918.93 in GUI results vs. 2367.83 in CLI results
>    Manure Carbon Input (i_m) (kg year^-1): 943.88 in GUI results vs. 0 in CLI results
>    Digestate carbon input (kg year^-1): 0 in both GUI and CLI


If you delete the generated CLI inputs files and then import the GUI farm file again, the inputs from manure will be added to the newly generated input files. The digestate C will be 0 in both cases unless a digestate application has been made to a field (and manure is being added to an existing Anaerobic Digester component on the farm).

Can you verify if the update fixes these issues for you?

**Comment by gfortinLogiag** [comment]
Thanks for the new version! I am now seeing different results with IPCCTier2 vs. ICBM and the ICBM results match those of the GUI versions perfectly.

Using the "Logiag_test_farm" I am still seeing different results between the CLI and the GUI versions when I select IPCCTier2 in both. I am not planning however to use IPCCTier2 for carbon modelling and I am fine if you choose to close this issue.

Thanks again!

**Comment by aaron-mcpherson** [comment]
@gfortinLogiag There is a new CLI installer that fixes the issues remaining with the IPCC Tier 2 you reported. If you import the farm from the GUI again, it will generate a new CLI settings file and a new CLI field file(s). Let me know if you encounter any other issues.
