### ISSUE TITLE
Crop GHG emission units are different in GUI and CLI output

### ISSUE THREAD

**Issue by RatnajitUTSC** [holos-aafc/Holos#54]
### Feature request.

I have run Holos CLI to read the emission report of crop fields in a .json file (created in GUI). I found emission reports for 2014, 2015 and 2016. In Holos CLI output, we have only N2O Direct [Kg N2O(ha)^-1] and N2O indirect [Kg N2O(ha)^-1]. In GUI output, we have Direct N2O (Kg CO2e), indirect N2O (Kg CO2e) and farm energy CO2 (Kg CO2e). Emission from crop field, CLI output unit was Kg N2O(ha)^-1 and GUI output was Kg CO2e. Also, in CLI output farm energy CO2 output as a column was not available in the crop emission output result file. How can we get the similar output from GUI and CLI? What is the conversion factor of N2O vs. CO2? Is this possible to fix the problem and get the same output from GUI and CLI? Also, please advice steps to execute CLI. Thanks in advance.

Contact: ratnajit.saha@mail.utoronto.ca

Attachment:
[Chatham#2016_0809_Emission 2016.xlsx](https://github.com/holos-aafc/Holos/files/12623436/Chatham.2016_0809_Emission.2016.xlsx)
[Chatham#2016_output-en-CA.csv.csv](https://github.com/holos-aafc/Holos/files/12623437/Chatham.2016_output-en-CA.csv.csv)
I couldn't upload farm json file, which was used to generate csv inputs. Please let me know, and send it if necessary by email.

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by aaron-mcpherson** [comment]
Hi @RatnajitUTSC there is a new CLI installation package ready for download. In this package, the energy emission calculations for the field results are included at the end of the output file. These new columns are labelled "Energy CO2" and "Upstream CO2". These refer to the emissions from energy emissions originating from the farm and emissions from the production of fertilizer (off-farm).

**Comment by aaron-mcpherson** [comment]
The various conversion factors that Holos uses can be found in this source file:

https://github.com/holos-aafc/Holos/blob/720adbb1de302266771e072835fa19829788791f/H.Core/CoreConstants.cs#L12

Here you can see how to convert from N2O to CO2 etc.
