### ISSUE TITLE
Crop GHG emission calculation and values for “Direct N₂O (kg CO₂e)” and “Indirect N₂O (kg CO₂e)” are different in CLI

### ISSUE THREAD

**Issue by RatnajitUTSC** [holos-aafc/Holos#60]
### Feature request.

I have run “Chatham#2016_0809.json” file in Holos GUI and then run the same .json file in Holos CLI. I found the farm energy emission columns are labelled as “Energy CO2 (kg)” and “Upstream CO2 (kg)” and the unit appears as CO2 equv. The reported emission values in Holos CLI for each crop in “Energy CO2 (kg)” and “Upstream CO2 (kg)” were same as Holos GUI output.
 
For crop GHG emission, Holos GUI provided output as “Direct N₂O (kg CO₂e)” and “Indirect N₂O (kg CO₂e)”. But in Holos CLI output units for those columns are not same as GUI output. To get the emission of total “Direct N₂O (kg CO₂e)” and “Indirect N₂O (kg CO₂e)”, I have added all together to get the total value:

**Direct N₂O (kg CO₂e) added the below values:**
N2O Direct (kg N2O (ha)^-1)
N2O-N from Synthetic Nitrogen (N2O-N_SNdirect) (kg N2O-N field^-1)
N2O-N From Crop Residues (N2O-N_CRNdirect) (kg N2O-N field^-1)
N2O-N from Nitrogen Mineralization (N2O-N_CRNmindirect) (kg N2O-N field^-1)
N2O-N from Organic Nitrogen (N2O-N_ONdirect) (kg N2O-N field^-1)
 
**Indirect N₂O (kg CO₂e) added the below values:**
N2O Indirect (kg N2O (ha)^-1)
N2O-N from Synthetic Nitrogen Leaching (N2O-N_SNleach) (kg N2O-N field^-1)
N2O-N from Mineral Leaching (N2O-N_minleach) (kg N2O-N field^-1)
N2O-N from Organic Nitrogen Leaching (N2O-N_ONleach) (kg N2O-N field^-1)
N2O-N from Synthetic Nitrogen Volatilization (N2O-N_SNvolatilization) (kg N2O-N field^-1)
 
I multiply the sum value of N2O with 273 (conversion factor from N2O to CO2 as mentioned in the GitHub). Then I compared the CLI output with GUI output for each crop rotation, field, and specific crop.  The CLI output for “Direct N₂O (kg CO₂e)”, “Indirect N₂O (kg CO₂e)” and Subtotal values were different compared to GUI output.
 
I have attached the excel file “Crop GHG_Holos CLI vs GUI_Differ” and “Chatham#2016_0809.json (in a .zip folder as .json file can not upload)” for your information, please find. Can you please check and suggest how I can get the same output from Holos GUI and CLI?

Thanks for your cooperation and look forward to hearing from you.

Attachment:
[Crop GHG_Holos CLI vs GUI_Differ.xlsx](https://github.com/holos-aafc/Holos/files/12740325/Crop.GHG_Holos.CLI.vs.GUI_Differ.xlsx)
[Chatham#2016_0809.zip](https://github.com/holos-aafc/Holos/files/12740476/Chatham.2016_0809.zip)

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct

**Comment by aaron-mcpherson** [comment]
Hi @RatnajitUTSC , thanks for the detailed comparison. There is a new installer package for the CLI that address this issue.

If you run the CLI to regenerate the inputs files, the indirect N2O will match what is being reported in the GUI.

One thing to note is that the values being displayed on the "Detailed Emissions Report" of the GUI are for the entire field, while the field output/results file from the CLI will list the indirect N2O with a per/ha value.
