### ISSUE TITLE
Fatal crash when running Holos CLI

### ISSUE THREAD

**Issue by gfortinLogiag** [holos-aafc/Holos#61]
### Contact Details

guillaume.fortin@logiag.com

### Expected Behaviour

I was trying to run Holos CLI on a new imported farm.

### Actual Behaviour

I am trying to run Holos CLI and it crashes right after importing the farm from the json file. I get the same behavior with an older json file that was previously working. There are no other farms defined in the Holos CLI Farms folder.

### Describe the Issue & Steps to Reproduce

1. Place the attached json in the Holos CLI farms folder: [Logiag_test_farm_with_rotation.zip](https://github.com/holos-aafc/Holos/files/12796638/Logiag_test_farm_with_rotation.zip)
3. Start Holos CLI
4. Say yes to importing a new farm

### Error Message

![image](https://github.com/holos-aafc/Holos/assets/135897587/264bcad1-6d4e-4283-b15a-aebf01f97cbc)

### Holos Version Number

4.0.0.490?

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by UrsakiUleth** [comment]
Hello @gfortinLogiag,

I have reproduced this bug on my end and am looking into the solution.

**Comment by gfortinLogiag** [comment]
When is a new installation package planned for the Holos CLI? At this time, I do not have the tools to create my own build and I am thus stuck with the crashing version. Thanks!

**Comment by aaron-mcpherson** [comment]
I am creating a new package this afternoon. I'll close this issue when it is ready so that you will get a notification

**Comment by aaron-mcpherson** [comment]
Hi @gfortinLogiag , there is a new installer ready. Can you verify this issue is resolved for you?

**Comment by gfortinLogiag** [comment]
Holos CLI now executes without any error. Thanks!

**Comment by aaron-mcpherson** [comment]
Thanks for reporting the issue.
