### ISSUE TITLE
Can not input amount of manure

### ISSUE THREAD

**Issue by robynjadischke** [holos-aafc/Holos#87]
### Contact Details

robyn.jadischke@agr.gc.ca

### Expected Behaviour

I would like to input 39230 kg/ha of manure on a canola field.

### Actual Behaviour

I have tried several times to input this number or numbers of the same magnitude. Sometimes it just says 0.0, sometimes it says -infinity, sometimes it takes the last digit off, sometimes it enters a totally random number instead. Numbers of this magnitude worked to be applied to corn in this model after several attempts of me trying to input the number.
![Screenshot (19)](https://github.com/holos-aafc/Holos/assets/151652038/900e4023-1254-4f1a-9d7f-7256363c05c6)

### Describe the Issue & Steps to Reproduce

1. Add manure to a canola (I am not sure if this is a canola-specific issue) field
2. Input an application rate over 10000

### Holos Version Number

4.0.0.504

### Code of Conduct

- [X] I agree to follow Holos' Code of Conduct.

**Comment by holos-aafc** [comment]
Hi Robyn,

Can you turn on the "Show additional information" button in the screenshot you sent and verify how much manure is produced? There will be a gauge showing how much is available for land application. Is the amounts being applied less that the total shown on the gauge?

**Comment by holos-aafc** [comment]
There is a new update for GUI (you will need to close and restart Holos to apply it). Once the update is applied, try removing the existing manure applications for the field and then re-adding the same manure application info. One thing to note is that if the user tries to apply more manure than is available on the field, Holos will automatically adjust the amount entered to the maximum amount available (amount of manure produced by animals on the farm in the specific year)

**Comment by robynjadischke** [comment]
Hi, I have restarted Holos and my computer and I believe there is enough manure to fulfill this application based on the "show additional details" tab. Is there an email address (for privacy reasons) I can send my file?

**Comment by aaron-mcpherson** [comment]
Closed as per email discussion
